### ISSUE TITLE
Output list total points

### ISSUE THREAD

**Issue by nexusno2000** [sprintska/shrimpbot#66] opened 2021-01-08 09:55 UTC
When we load a list, can you have the bot output total points in the chat? If that value is stored somewhere.

Pro: neat.
Con: if someone changes the log file, the changes won't be reflected in points.

**Comment by sprintska** [comment] 2021-01-08 22:34
Duplicate of #15

**Comment by sprintska** [comment] 2021-04-24 08:31
Closed as duplicate of #15 (cause I didn't do it correctly 3 months ago).

**Closed as completed by sprintska** 2021-04-24 08:31 UTC
Labels: enhancement
